/* WARNING: This file is auto-generated by build.js */
module.exports = {
  "address":require("./src/address.js"),
  "block":require("./src/block.js"),
  "hash":require("./src/hash.js"),
  "identity":require("./src/identity.js"),
}