/* WARNING: This file is auto-generated by build.js */
module.exports = {
  "block":require("./src/block.js"),
  "blockHeader":require("./src/blockHeader.js"),
  "hash":require("./src/hash.js"),
  "transaction":require("./src/transaction.js"),
  "utils":require("./src/utils.js"),
  "wallet":require("./src/wallet.js"),
  "words":require("./src/words.js"),
}