/* WARNING: This file is auto-generated by build.js */
module.exports = {
  "block":require("./src/block.js"),
  "hash":require("./src/hash.js"),
  "identity":require("./src/identity.js"),
  "transaction":require("./src/transaction.js"),
}